services:
  ollama:
    image: ollama/ollama:0.11.4
    container_name: llm-rag-examples-ollama
    hostname: llm-rag-examples-ollama
    ports:
      - 11434:11434
    volumes:
      - ./ollama/data:/root/.ollama







































































































